### ISSUE TITLE
希望提供更加灵活的方式配置 solution 和配置文件的地址

### ISSUE THREAD

**Issue by creamidea** [nowa-webpack/nowa2#6]
希望提供一种机制，可以从命令行上配置 solution。如此，配置文件中就不必填写 solution。

另外，希望提供参数 `-f`，用于指定使用的 nowa.config.js 配置文件。

综合上面 2 处改造，可以让 solution 的配置更加灵活。更加聚焦 solution 所抽象的领域。

**Comment by creamidea** [comment]
初步方案确定

1. nowa 本身将 solution 填入 package.json
```
nowa: {
  solution: '@ali/nowa-recore-solution'
}
```

2. 修改配置名称交给 solution 自身决定，可以复写 `load-config` 相关配置

**Comment by tommytroylin** [comment]
Close this in 29048b3ebee980349134eea093ed114378dd5e14
